github:
  owner: codecov
  repo: codecov-cli

changelogPolicy: auto

targets:
  - name: github
    tagPrefix: v
    checksums:
      - algorithm: sha256
    includeNames: /^(codecov|codecov_)cli.*/i

  - name: pypi
    includeNames: /codecov_cli-*/i
