name ?= codecovcli
# Semantic versioning format https://semver.org/
tag_regex := ^v([0-9]{1,}\.){2}[0-9]{1,}([-_]\w+)?$

lint:
	pip install black==22.3.0 isort==5.10.1
	black codecov_cli
	isort --profile=black codecov_cli -p staticcodecov_languages
	black tests
	isort --profile black tests

tag.release:
ifeq ($(shell echo ${version} | egrep "${tag_regex}"),)
	@echo "Version '${version}' is not a valid git tag.\nUsage: make tag.release version=v0.0.0"
else
	@echo "Tagging new release ${version}"
	git tag -a ${version} -m "Autogenerated release tag for codecov-cli"
	git push origin ${version}
endif