name ?= codecovcli
# Semantic versioning format https://semver.org/
tag_regex := ^v([0-9]{1,}\.){2}[0-9]{1,}([-_]\w+)?$

lint:
	pip install black==22.3.0 isort==5.10.1
	black codecov_cli
	isort --profile=black codecov_cli -p staticcodecov_languages
	black tests
	isort --profile black tests

tag.release:
ifeq ($(shell echo ${version} | egrep "${tag_regex}"),)
	@echo "Version '${version}' is not a valid git tag.\nUsage: make tag.release version=v0.0.0"
else
	@echo "Tagging new release ${version}"
	git tag -a ${version} -m "Autogenerated release tag for codecov-cli"
	git push origin ${version}
endif

local_upload:
ifeq (${token},)
	@echo "token must be set.\nUsage: make local_upload token=token code=code"
else
ifeq (${code},)
	@echo "code must be set.\nUsage: make local_upload token=token code=code"
else
	@echo "Creating commit"
	codecovcli create-commit -t ${token} --git-service github
	@echo "Creating report with code ${code}"
	codecovcli create-report -t ${token} --code ${code} --git-service github
	@echo "Running tests"
	pytest --cov
	@echo "Uploading coverage to Codecov"
	codecovcli do-upload --fail-on-error -t ${token} --plugin pycoverage --report-code ${code} --flag local_upload
endif
endif